### ISSUE TITLE
Connection 'default' is already active.

### ISSUE THREAD

**Issue by chrisvdwerf** [oliehoek-research/BscProj-aienvs#3]
I was wondering if you have an easy solution for the problem below. For the GridSumoEnv a simple 
kernel reset seems to be sufficient most of the time, but when I try to use the SymoGymAdapter directly it gives me this error all the time even after a complete reboot. I already spent quite a lot of time finding a solution, so I was wondering if you might know an easy fix for this.

![image](https://user-images.githubusercontent.com/18056780/80798798-7f4f7580-8ba5-11ea-9310-f2fd67b45105.png)

**Comment by chrisvdwerf** [comment]
@JINKEHE I tried different paramater configurations. Maybe an easy example would be the default configuration which uses the four_grid scenario.
```
from aienvs.Sumo.SumoGymAdapter import SumoGymAdapter
SumoGymAdapter({'seed': None})
```

**Comment by chrisvdwerf** [comment]
GridSumoEnv creates a SumoGymAdapter with the following paramters:
```
    'gui': False,
    'scene': 'grid_2x2',
    'tlphasesfile': 'grid_2x2.tll.xml',
    'box_bottom_corner': (0, 0),
    'box_top_corner': (300, 300),
    'resolutionInPixelsPerMeterX': 0.1,
    'resolutionInPixelsPerMeterY': 0.1,
    'y_t': 6,
    'car_pr': 0.1,
    'car_tm': 1000,
    'route_starts': ['e_0_1_l_1_1 l_1_1_l_2_1 l_2_1_e_3_1', 'e_0_2_l_1_2 l_1_2_l_2_2 l_2_2_e_3_2', 'e_1_0_l_1_1 l_1_1_l_1_2 l_1_2_e_1_3', 'e_2_0_l_2_1 l_2_1_l_2_2 l_2_2_e_2_3'],
    'route_min_segments': 0,
    'route_max_segments': 0,
    'route_ends': [],
    'generate_conf': True,
    'libsumo': False,
    'waiting_penalty': 1,
    'new_reward': False,
    'lightPositions': {},
    'scaling_factor': 1.0,
    'maxConnectRetries': 50,
    'seed': None,
    'shape': (2, 2),
    'lane_length': 100
```
Appearently you often get to see the connection error when one or more of the parameters are malformed. For example, changing one of the edges in `route_starts` to one that does not exist.

**Comment by JINKEHE** [comment]
> @JINKEHE I tried different paramater configurations. Maybe an easy example would be the default configuration which uses the four_grid scenario.
> 
> ```
> from aienvs.Sumo.SumoGymAdapter import SumoGymAdapter
> SumoGymAdapter({'seed': None})
> ```

I tried this.

First of all, I think the error "TraCIException: Connection 'default' is already active" which is shown by the jupyter notebook is confusing. If you open the terminal that starts the jupyter notebook you will see the true error. 

<img width="546" alt="image" src="https://user-images.githubusercontent.com/22544428/80942313-c4adb600-8de4-11ea-8b39-e05730d414e9.png">

which apparently happens because there is an error with the sumo configuration. 

I dived deeper into this and found that it happens because you didn't specify any valid routes by the parameter 'route_starts' for the generation of vehicles and somehow the sumo gym adaptor generates itself some routes that have no edges, which caused the error in the terminal.

For example, if you try 

`from aienvs.Sumo.SumoGymAdapter import SumoGymAdapter
SumoGymAdapter({'seed': None, 'route_starts':['1_0']})`

then it will work

**Comment by JINKEHE** [comment]
> GridSumoEnv creates a SumoGymAdapter with the following paramters:
> 
> ```
>     'gui': False,
>     'scene': 'grid_2x2',
>     'tlphasesfile': 'grid_2x2.tll.xml',
>     'box_bottom_corner': (0, 0),
>     'box_top_corner': (300, 300),
>     'resolutionInPixelsPerMeterX': 0.1,
>     'resolutionInPixelsPerMeterY': 0.1,
>     'y_t': 6,
>     'car_pr': 0.1,
>     'car_tm': 1000,
>     'route_starts': ['e_0_1_l_1_1 l_1_1_l_2_1 l_2_1_e_3_1', 'e_0_2_l_1_2 l_1_2_l_2_2 l_2_2_e_3_2', 'e_1_0_l_1_1 l_1_1_l_1_2 l_1_2_e_1_3', 'e_2_0_l_2_1 l_2_1_l_2_2 l_2_2_e_2_3'],
>     'route_min_segments': 0,
>     'route_max_segments': 0,
>     'route_ends': [],
>     'generate_conf': True,
>     'libsumo': False,
>     'waiting_penalty': 1,
>     'new_reward': False,
>     'lightPositions': {},
>     'scaling_factor': 1.0,
>     'maxConnectRetries': 50,
>     'seed': None,
>     'shape': (2, 2),
>     'lane_length': 100
> ```
> 
> Appearently you often get to see the connection error when one or more of the parameters are malformed. For example, changing one of the edges in `route_starts` to one that does not exist.

this configuration seems working fine for me? @chrisvdwerf

**Comment by JINKEHE** [comment]
does this help? @chrisvdwerf

**Comment by chrisvdwerf** [comment]
Yes, thank you
